config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get 'home/about' => 'homes#about'
  resources :books do
  resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "search" => "searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20}


  validates :introduction, length: { maximum: 50 }



  def get_profile_image
   unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end


  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def show
   @user = User.find(params[:id])
   @books = @user.books
   @new_book = Book.new
  end
  
  def edit
   @user = User.find(params[:id])
  
   if @user == current_user
      render :edit
   else
      redirect_to user_path(current_user)
   end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully.."
      redirect_to user_path(@user)
    else
       render :edit
    end
  end

 def new
    @user = User.new
 end
 
 
 

 def index
   @user = current_user
   @book = Book.new
   @books = Book.all
   @users = User.all
 end
 
 def create
  @user = User.new(user_params)
  @user.user_id = current_user.id
  if @user.save
    redirect_to edit_user_path
  else
    render user_path
  end
 end
 
 def destroy
    @user = current_user
    if @user.destroy
       flash[:notice]="successfully"
    redirect_to root_path
    end
 end
 
 private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)  
  end
end

def book_params
    params.require(:book).permit(:title, :body)
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<p id="notice"></p>
<div class="col-md-3">

<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <ul>
 <%= book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<h2>User info</h2>
<% if user.profile_image.attached? %>
  <%= image_tag user.profile_image,size:"100x100" %>
<% else %>
  <%= image_tag 'no_image', size: "50x50" %>
<% end %>

<table class="table">
<tbody>

<tr>
 <th>name</th>
 <th><%= user.name %></th>
</tr>

<tr>
 <th>introduction</th>
 <th><%= user.introduction %></th>
 <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</tr>
</tbody>
</table>

<div class="row">
<%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %><i class="fas fa-user-cog"></i><% end %></div>








<h2 class= "mt-3">New book</h2>
<%= form_with model: book do |f| %>

<div class= "form-group">
 <label>Title</label>
<br>
 <input class="form-control book_title" type="text" name="book[title]" id="book_title">
</div>
<div class= "form-group">
 <label>Opinion</label>
<br>

<textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
</div>


 <div class="form-group">
  <%= f.submit class:"btn btn-success" %>
 </div>
<% end %>


</div>

app/views/users/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'books/error', model: @user %>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>



<div class= "form-group">
 <label>Name</label><br>
 <%= f.text_field :name  %>
</div>

<div class= "fotm-group">
 <label>image</label><br>
 <%= f.file_field :profile_image, accept: "image/*" %>
</div>

<div class= "form-group">
 <label>introduction</label><br>
 <%= f.text_area :introduction %>
</div>

<div class= "form-group">
 <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
</div>

  <% end %>
</div>
 </div>
  </div>
  
  <%= render'users/footer' %>

app/views/users/followers.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/follows.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">

<%= render'users/info', user:@user,book:@book %>


<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
   <tr>
     <td>
      <% if user.profile_image.attached? %>
        <%= image_tag user.profile_image, size: "50x50" %>
      <% else %>
        <%= image_tag 'no_image', size: "50x50" %>
      <% end %>
     </td>
     <td>
       <%= user.name %>
     </td>
      <td><%= render "relationships/btn", user: user %></td>
     <td>
       <%= link_to "Show", user_path(user) %>
     </td>
   </tr>
   <% end %>
  </tbody>
</table>

</div>
</div>
</div>
<%= render'users/footer' %>

app/views/users/show.html.erb
<p id="notice"></p>
 <div class="container px-5 px-sm-0">


   <% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>

    <% end %>
</div>
  <div class="row">

<%= render'users/info', user:@user,book:@new_book %>

<% if @new_book.errors.any? %>
  <%= @new_book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <%= @new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
<% @books.each do |book| %>
   <tr>
     <td>
     <%= link_to user_path(book.user.id) do %>
      <% if book.user.profile_image.attached? %>
        <%= image_tag book.user.profile_image, size: "50x50" %>
      <% else %>
        <%= image_tag 'no_image', size: "50x50" %>
      <% end %>
     <% end %>
     </td>
     <td>
       <%= link_to book.title, book_path(book) %>
     </td>
     <td>
       <%= book.body %>
     </td>
     <td>コメント数: <%= book.book_comments.count %></td>

     <td class= <%="favorite_buttons_"+ book.id.to_s%>>
     <%= render "favorites/btn", book: book %>
     </td>

   </tr>
   <% end %>
  </tbody>
</table>
</div>
 </div>
  </div>
<%= render'users/footer' %>